# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name fit_rpagp_cpp
#' @title The C++ backend for the RPAGP model sampler.
#' @description This is the core C++ function that runs the MCMC sampler.
#' It is not intended to be called directly by the user. Please use the
#' R wrapper function \code{fit_rpagp()} instead.
#' @param y A matrix of observed trial data.
#' @param n_iter The total number of MCMC iterations.
#' @param theta0 A list of initial parameter values.
#' @param hyperparam A list of hyperparameter values.
#' @param seed An integer seed for reproducibility.
#' @keywords internal
fit_rpagp_cpp <- function(y, n_iter, theta0, hyperparam, seed = 0L) {
    .Call(`_rpagp_fit_rpagp_cpp`, y, n_iter, theta0, hyperparam, seed)
}

